#!/bin/sh
# shellcheck disable=SC2155
# Profile file, runs on login. Environmental variables are set here.
#  ┏┓┳┓┏┓┏┓┳┓ ┏┓
#  ┃┃┣┫┃┃┣ ┃┃ ┣
#  ┣┛┛┗┗┛┻ ┻┗┛┗┛
#
#  ┓ ┏┓┳┳┳┓┏┓┓┏  ┓┏┓┏┏┓┳┓┓ ┏┓┳┓┳┓  ┓ ┳┓┏┓┏┓  ┏┓  ┏┓┓┏┏┓┳┓
#  ┃ ┣┫┃┃┃┃┃ ┣┫  ┣┫┗┫┃┃┣┫┃ ┣┫┃┃┃┃  ┃ ┃┃┫ ┣   ┣┫  ┃ ┣┫┣┫┃┃
#  ┗┛┛┗┗┛┛┗┗┛┛┗  ┛┗┗┛┣┛┛┗┗┛┛┗┛┗┻┛  ┗┛┻┛┗┛┗┛  ┛┗  ┗┛┛┗┛┗┻┛
#

# Add all directories in `~/.local/bin` to $PATH
export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

unsetopt PROMPT_SP 2>/dev/null

# Default programs:
export EDITOR="nvim"
export TERMINAL="foot"
export TERMINAL_PROG="foot"
export BROWSER="zen-browser"

# Change the default crypto/weather monitor sites.
# export CRYPTOURL="rate.sx"
# export WTTRURL="wttr.in"

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
export HISTFILE="$XDG_DATA_HOME/history"
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"

# Other program settings:
export LESS="R"
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"

# Fzf OPTS
export FZF_DEFAULT_OPTS="--style=full --height=90% --pointer '>' \
                --color 'pointer:green:bold,bg+:-1:,fg+:green:bold,info:blue:bold,marker:yellow:bold,hl:gray:bold,hl+:yellow:bold' \
                --input-label ' Search ' --color 'input-border:blue,input-label:blue:bold' \
                --list-label ' Results ' --color 'list-border:green,list-label:green:bold' \
                --preview-label ' Preview ' --color 'preview-border:magenta,preview-label:magenta:bold'"

#  ┓ ┏┓┳┳┳┓┏┓┓┏  ┓┏┓┏┏┓┳┓┓ ┏┓┳┓┳┓
#  ┃ ┣┫┃┃┃┃┃ ┣┫  ┣┫┗┫┃┃┣┫┃ ┣┫┃┃┃┃
#  ┗┛┛┗┗┛┛┗┗┛┛┗  ┛┗┗┛┣┛┛┗┗┛┛┗┛┗┻┛
#
# Starting Wayland
if [ -z "$DISPLAY" ] && [ "${XDG_VTNR}" -eq 1 ]; then
    exec dbus-run-session Hyprland
fi
