#
#  ┏┓┏┳┓┏┓┳┓┏┓┓┏┳┏┓  ┳┳┓┳┳┓┳┳┳┓┏┓┓   ┳┓┓ ┳┳┏┓┓┏
#  ┗┓ ┃ ┣┫┣┫┗┓┣┫┃┃┃  ┃┃┃┃┃┃┃┃┃┃┣┫┃   ┣┫┃ ┃┃┗┓┣┫
#  ┗┛ ┻ ┛┗┛┗┗┛┛┗┻┣┛  ┛ ┗┻┛┗┻┛ ┗┛┗┗┛  ┻┛┗┛┗┛┗┛┛┗
#  Minimalist but beautiful

add_newline = true

format = """($git_metrics\n)$cmd_duration\
$hostname\
$jobs\
$sudo\
$character"""

right_format = """
$directory\
$git_branch\
$git_status\
$c\
$cpp\
$java\
$lua\
$nodejs\
$python\
$golang\
$rust\
$battery\
$time"""

[fill]
symbol = ' '

# Character
[character]
format = "$symbol "
success_symbol = "[󰺕 ](bright-purple)"
error_symbol = "[ ](bright-red)"
vimcmd_symbol = "[󰝤 ](dimmed green)"
vimcmd_replace_one_symbol = " "
vimcmd_replace_symbol = " "
vimcmd_visual_symbol = " "

# Sudo
[sudo]
format = "[$symbol]($style)"
style = "bright-purple"
symbol = "⋈┈"
disabled = false

# Username
[username]
style_user = "bright-yellow bold"
style_root = "purple bold"
format = "[ $user]($style) "
disabled = false
show_always = false

# Directory
[directory]
home_symbol = " "
truncation_length = 2
truncation_symbol = "󰝣 "
read_only = " 󰌾 "
use_os_path_sep = true
style = "bright-purple"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bright-purple'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'

# Cmd Duration
[cmd_duration]
format = "[󰪠 $duration ](white)"

# Jobs
[jobs]
format = "[$symbol$number]($style) "
style = "white"
symbol = "[✦ ](red)"

# Time
[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "dimmed white"

# Battery
[battery]
format = "[ $symbol$percentage]($style)"
full_symbol = "󰂅 "
charging_symbol = "[󱟠 ](green)"
discharging_symbol = "[󱟞 ](purple)"
unknown_symbol = "󰂅 "
empty_symbol = "󰢟 "

[[battery.display]]
threshold = 20
style = "bright-red"

[[battery.display]]
threshold = 60
style = "bright-green"

[[battery.display]]
threshold = 70
style = "bright-green"

# Git Branch
[git_branch]
format = " [$symbol$branch(:$remote_branch)]($style)"
symbol = "[ ](bright-blue)"
style = "bright-blue"
truncation_symbol = "⋯"
truncation_length = 11
only_attached = true

# Git Metrics
[git_metrics]
format = '([󰶣 $added]($added_style)) ([󰶡 $deleted]($deleted_style))'
added_style = 'dimmed green'
deleted_style = 'dimmed red'
ignore_submodules = true
disabled = false

# Git Status
[git_status]
format = '( [\[$all_status$ahead_behind\]]($style))'
style = "red"
stashed = "[${count}*](bright-green)" 
modified = "[${count}+](bright-yellow)" 
deleted =  "[${count}-](bright-red)" 
conflicted =  "[${count}~](bright-red)" 
ahead = "⇡${count}"
behind = "⇣${count}"
untracked = "[${count}?](bright-blue)" 
staged = "[${count}+](bright-green)" 

# Languages

[lua]
format = " [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = "󰢱 "
style = "bright-cyan"

[nodejs]
format = " [ ($version)](bright-green)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[python]
format = " [${symbol}${version}]($style)"
symbol = "[ ](bright-blue)"
version_format = "${raw}"
style = "bright-blue"

[rust]
format = " [$symbol$version]($style)"
symbol = " "
version_format = "${raw}"
style = "red"

[c]
symbol = " "
style = "bright-yellow"
format = " [$symbol($version(-$name))]($style)"

[cpp]
symbol = " "
style = "bright-yellow"
format = " [$symbol($version(-$name))]($style)"

[conda]
symbol = " "
style = "bright-purple"
format = " [$symbol$environment]($style)"

[golang]
symbol = " "
style = "bright-blue"
format = " [$symbol($version )]($style)"

[java]
symbol = "󰬷 "
style = "bright-purple"
format = " [${symbol}(${version} )]($style)"
