#  ┏┓┏┳┓┏┓┳┓┏┓┓┏┳┏┓
#  ┗┓ ┃ ┣┫┣┫┗┓┣┫┃┃┃
#  ┗┛ ┻ ┛┗┛┗┛┛┗┻┣┛

add_newline = true
continuation_prompt = "∙  ┆ "

format = "$os$directory$container$git_branch $git_status$python$nodejs$lua$rust$java$c$golang$cmd_duration$status$line_break$character"

[character]
success_symbol = "[❯ ](bold bright-purple)"
error_symbol = "[❯ ](bold bright-red)"
vimcmd_symbol = "[❮ ](bold bright-purple)"
vimcmd_visual_symbol = "[❮ ](bold bright-blue)"
vimcmd_replace_symbol = "[❮ ](bold bright-white)"
vimcmd_replace_one_symbol = "[❮ ](bold bright-white)"

[status]
symbol = "✗"
not_found_symbol = "󰍉 Not Found"
not_executable_symbol = " Can't Execute"
sigint_symbol = " "
signal_symbol = "󱑽 "
success_symbol = ""
format = "[$symbol](bright-red)"
map_symbol = true
disabled = false

[cmd_duration]
min_time = 1000
format = "[$duration ](bright-yellow)"

[container]
symbol = " 󰏖"
format = "[$symbol ](bright-yellow dimmed)"

[directory]
format = " [](fg:bright-black)[$path](bg:bright-black fg:bright-white)[](fg:bright-black) [$read_only](fg:bright-yellow)"
read_only = " "
truncate_to_repo = true
truncation_length = 4
truncation_symbol = ""

[git_branch]
symbol = ""
style = ""
format = "[ $symbol $branch](bright-purple)(:$remote_branch)"

[os]
disabled = false
format = "$symbol"

[os.symbols]
Arch = "[ ](bright-blue)"
Alpine = "[ ](bright-blue)"
Debian = "[ ](bright-red)"
EndeavourOS = "[ ](bright-purple)"
Fedora = "[ ](bright-blue)"
NixOS = "[ ](bright-blue)"
openSUSE = "[ ](bright-green)"
SUSE = "[ ](bright-green)"
Ubuntu = "[ ](bright-magenta)"
Macos = "[ ](bright-white)"

[python]
symbol = ""
format = "[$symbol ](bright-yellow)"

[nodejs]
symbol = "󰛦"
format = "[$symbol ](bright-blue)"

[bun]
symbol = "󰛦"
format = "[$symbol ](bright-blue)"

[deno]
symbol = "󰛦"
format = "[$symbol ](bright-blue)"

[lua]
symbol = "󰢱"
format = "[$symbol ](bright-blue)"

[rust]
symbol = ""
format = "[$symbol ](bright-red)"

[java]
symbol = ""
format = "[$symbol ](bright-red)"

[c]
symbol = ""
format = "[$symbol ](bright-blue)"

[golang]
symbol = ""
format = "[$symbol ](bright-blue)"

[dart]
symbol = ""
format = "[$symbol ](bright-blue)"

[elixir]
symbol = ""
format = "[$symbol ](bright-purple)"
